[build]
  # Build command
  command = "npm run build"
  # Output directory for built files
  publish = "dist"

# SPA redirect rule - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

